language: java
jdk:
  - openjdk8
dist: trusty
addons:
  sonarcloud:
    organization: $sonarcloud_organization_key
    token: $sonarcloud_token
    branches:
      - master
      - next
matrix:
  fast_finish: true
before_install:
  - pip install --user codecov
script:
  - mvn clean
  - mvn test
  - mvn install -Pserver
after_success:
  - codecov
  - mvn sonar:sonar
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: target/*.war
  skip_cleanup: true
  on:
    tags: true
