language: java
jdk:
  - openjdk8
dist: trusty
matrix:
  fast_finish: true
before_install:
  - pip install --user codecov
script:
  - mvn clean
  - mvn test
  - mvn install -Pserver
after_success:
  - codecov
  - mvn sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$sonarcloud_token -Dsonar.projectKey=me.xstr:api -Dsonr.brach=$TRAVIS_BRANCH
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: target/*.war
  skip_cleanup: true
  on:
    tags: true
